# Generated by Django 2.2.2 on 2019-06-12 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driverscoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='last_access_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 12, 30, 44, 111761)),
        ),
    ]
