# Generated by Django 2.2.2 on 2019-06-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driverscoring', '0002_driver_last_access_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='last_access_time',
        ),
    ]
